### ISSUE TITLE
GCC 12 rebuild

### ISSUE THREAD

**Issue by ioraff** [kiss-community/repo#64]
core:
- [x] baseinit
- [x] baselayout
- [x] binutils
- [x] bison
- [x] busybox
- [x] bzip2
- [x] curl
- [x] flex
- [x] gcc
- [x] git
- [x] grub
- [x] kiss
- [x] linux-headers
- [x] m4
- [x] make
- [x] musl
- [x] openssl
- [x] pigz
- [x] xz
- [x] zlib

extra:
- [x] adwaita-icon-theme
- [x] alsa-lib
- [x] alsa-utils
- [x] atk
- [x] bkeymaps
- [x] cairo
- [x] cbindgen
- [x] ccache
- [x] clang
- [x] cmake
- [x] dhcpcd
- [x] dosfstools
- [x] e2fsprogs
- [x] efibootmgr
- [x] efivar
- [x] eiwd
- [x] expat
- [x] ffmpeg
- [x] firefox
- [x] firefox-privacy
- [x] fontconfig
- [x] freetype-harfbuzz
- [x] gdk-pixbuf
- [x] glib
- [x] gnugrep
- [x] gnupg1
- [x] gtk+3
- [x] hicolor-icon-theme
- [x] intel-vaapi-driver
- [x] json-c
- [x] kirc
- [x] lame
- [x] libass
- [x] libelf
- [x] libffi
- [x] libjpeg-turbo
- [x] libogg
- [x] libpng
- [x] libtheora
- [x] libudev-zero
- [x] libva
- [x] libva-utils
- [x] libvorbis
- [x] libvpx
- [x] libwebp
- [x] llvm
- [x] man-pages
- [x] mandoc
- [x] mdevd
- [x] mesa
- [x] meson
- [x] mold
- [x] mpv
- [x] mutt
- [x] nasm
- [x] ncurses
- [x] nodejs
- [x] opendoas
- [x] openresolv
- [x] openssh
- [x] opus
- [x] pango
- [x] pcre
- [x] perl
- [x] pkgconf
- [x] python
- [x] rust
- [x] samurai
- [x] scdoc
- [x] sqlite
- [x] ssu
- [x] strace
- [x] ttf-croscore
- [x] tzdata
- [x] util-linux
- [x] vim
- [x] wpa_supplicant
- [x] x264
- [x] x265
- [x] xvidcore
- [x] zstd

wayland:
- [x] foot
- [x] foot-pgo
- [x] grim
- [x] libdrm
- [x] libinput
- [x] libpciaccess
- [x] libseat
- [x] libxkbcommon
- [x] pixman
- [x] slurp
- [x] sway 411025f
- [x] sway-no-seat
- [x] sway-tiny
- [x] wayclip
- [x] wayland
- [x] wayland-protocols
- [x] wbg
- [x] wlroots
- [x] wlsunset
- [x] xkeyboard-config
